name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: "CI/CD"
    runs-on: ubuntu-latest
    environment: testnet
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: ['20.x']

    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      PRIVATE_KEY2: ${{ secrets.PRIVATE_KEY2 }}
      PRIVATE_KEY3: ${{ secrets.PRIVATE_KEY3 }}
      ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}

    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@91182cccc01eb5e619899d80e4e971d6181294a7 # v2.10.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Node.js
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4.1.0
        with:
          node-version: ${{ matrix.node-version }}
    
      - name: Install Yarn
        run: npm install --global yarn

      - name: Cache Yarn Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/yarn
            node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install Dependencies
        run: yarn install

      - name: Compile
        run: yarn run compile

      - name: Run Tests
        run: yarn run test
        continue-on-error: true
        
      - name: Extract and publish ABIs
        run: |
            mkdir -p data/abis
            find ./artifacts/contracts -type f -name "*.json" ! -name "*.dbg.json" -exec cp {} data/abis/ \;

      # Setup git and GPG
      - name: Import GPG Key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | base64 --decode > private.key
          gpg --batch --import private.key
          rm private.key
          git config --global user.signingkey ${{ secrets.GPG_KEY_ID }}
          git config --global commit.gpgsign true
          git config --global user.email "bot@gashgraph.com"
          git config --global user.name "Bot"
            
      - name: Commit and push ABI changes
        run: |
          git fetch origin ${{ github.head_ref }}
          git checkout ${{ github.head_ref }}
          git add ./data/abis/*.json
          git diff-index --quiet HEAD || git commit -S -m "Auto-commit ABIs [ci skip]" --author="Bot <bot@gashgraph.com>"
          git push origin HEAD:${{ github.head_ref }}
      
          
        
