name: CI

on:
  push:
    branches:
      - main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest
    environment: testnet #change to mainnet before production

    strategy:
      matrix:
        node-version: ['20.x']

    env:
      RPC_URL: ${{ secrets.RPC_URL }}
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}

    steps:      
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Yarn
        run: npm install --global yarn

      - name: Install Dependencies
        run: yarn install

      - name: Compile
        run: yarn run compile

      - name: Run Tests
        run: yarn run test

      - name: Extract and publish ABIs
        run: |
          mkdir -p data/abis
          cp artifacts/contracts/**/*.json data/abis/
          
#      - name: Get release ID
#        id: get_release
#        uses: bruceadams/get-release@v1.3.2
#        env:
#          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload ABI
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_options: '--no-verify --signoff'
 #         repo_token: ${{ secrets.GITHUB_TOKEN }}
          file_pattern: './data/abis/*.json'


          
#      - name: Commit and push if there are changes
#        run: |
#          git config --global user.name 'github-actions'
#          git config --global user.email 'github-actions@github.com'
#          git add data/abis/
#          git commit -m "Update ABIs" -a || echo "No changes to commit."
#          git pull
#          git push

      - name: Run Deploy
        run: yarn run deploy --network testnet #change to mainnet before production
